[build]
  command = "npx @11ty/eleventy"
  publish = "_site"

[functions]
  directory = "src/netlify/functions"

[[redirects]]
  from = "http:///*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/blog.html"
  to = "/blog/"
  status = 301
  force = true

[[redirects]]
  from = "/cv.html"
  to = "/cv/"
  status = 301
  force = true

[[redirects]]
  from = "/privacy.html"
  to = "/privacy/"
  status = 301
  force = true

[[redirects]]
  from = "/terms.html"
  to = "/terms/"
  status = 301
  force = true

[[redirects]]
  from = "/admin/finance/"
  to = "/admin/family/"
  status = 301
  force = true

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/callback"
  status = 200
