// src/netlify/functions/generate-image.js
const { GoogleGenAI } = require("@google/genai");

exports.handler = async (event) => {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: 'Method Not Allowed' };
  }

  const { GEMINI_API_KEY } = process.env;
  if (!GEMINI_API_KEY) {
    return {
      statusCode: 500,
      body: JSON.stringify({ error: "Missing GEMINI_API_KEY environment variable" }),
    };
  }

  const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

  try {
    const { title, keywords } = JSON.parse(event.body || '{}');

    // Step 1: Generate the image using Imagen 3
    const response = await ai.models.generateImages({
      model: 'imagen-3.0-generate-001',
      prompt: `A highly detailed, professional, photorealistic featured image for a blog post titled "${title}". Keywords: ${keywords.join(', ')}. Style: Modern, clean, professional photography with soft natural lighting. No text or logos.`,
      config: {
        numberOfImages: 1,
        aspectRatio: '16:9'
      },
    });

    if (!response.generatedImages || response.generatedImages.length === 0) {
      throw new Error("No image was generated by Gemini.");
    }

    const generatedImage = response.generatedImages[0];
    const base64Image = generatedImage.image.imageBytes;

    return {
      statusCode: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        base64: base64Image,
        contentType: 'image/png'
      }),
    };
  } catch (error) {
    return {
      statusCode: 500,
      body: JSON.stringify({ error: error.message }),
    };
  }
};